language: python
python: 3.9
env:
  global:
    - CODECOV_TOKEN='68b4c3b6-ae9f-45aa-a430-d5fde523a073'

    - TOX_ENV=py39
install:
- pip install tox
script:
- tox -e $TOX_ENV
branches:
  only:
  - main
notifications:
  email: false 