#
# Message in A bottle Docker Compose file
#

version: "3.6"

services:
  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      # this is only for development purpose
      - "5342:5342"
    env_file:
      - env_file

  mib_lottery:
    <<: &mib_lottery
      # Building the image
      image: "mib-lottery:latest"
      build:
        context: .
        dockerfile: Dockerfile 

    ports:
     - "5000:5000"
    env_file:
      - env_file
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db
      - migrations
  
  lottery-bg:
      depends_on:
        - celery
        - lottery
      build: .
      env_file:
        - env_file
      environment:
        - REDIS_HOST=redis
      command: python3 -u subscribers.py
      links:
        - redis
  celery:
    depends_on:
        - redis-celery
        - mib-lottery
    build: .
    restart: always
    command: celery -A mib.background worker --loglevel=info
    links:
        -  redis-celery
  redis:
      image: "redis:alpine"
      container_name: rd01
      command: --port 6379
      ports:
        - "6379:6379"
  redis-celery:
      image: "redis:alpine"
      container_name: rd02
      command: --port 6380
      ports:
        - "6380:6380"
  migrations:
    #
    # this service is used to apply migrations on db
    #
    <<: *mib_lottery
    command: flask db upgrade
    env_file:
      - env_file
    environment:
      - POSTGRES_HOST=db
    restart: on-failure

# Declaring all volumes
volumes:
  pgdata: 