openapi: "3.0.1"
info:
  title: Lottery Service API
  description: Lottery Microservice of Message in a Bottle Application
  version: "0.1"

servers:
  - url: /

paths:
  /lottery:
    get:
      summary: get the next lottery date and the list of participants
      tags:
        - Lottery
      operationId: mib.resources.lottery.get_next_lottery
      responses:
        200:
          description: returns the next lottery date and the participants
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lottery'
  
  /lottery/participate:
    put:
      summary: participate in the next lottery
      tags:
        - Lottery
      operationId: mib.resources.lottery.participate
      requestBody:
        description: id = user id of the new participant  choice = number chosen
        required: true
        content: 
          application/json:
            schema:
              $ref: '#/components/schemas/Participant'
      responses:
        200:
          description: Already participated
        400:
          description: Invalid choice
        201:
          description: Lottery participation added        
  
  /lottery/{participant_id}:
    get:
      summary: returns the choice of a participant
      tags:
        - Lottery
      parameters:
        - in: path
          name: participant_id
          required: true
          schema:
            type: integer
            format: int64
            description: user id of the participant
      operationId: mib.resources.lottery.get_choice
      responses:
        200:
          description: Participant found and choice returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  choice:
                    type: integer
        404:
          description: No participant found with the given participant_id
    delete:
      summary: removes a participant
      tags:
        - Lottery 
      parameters:
        - in: path
          name: participant_id 
          required: true
          schema:
            type: integer 
            format: int64
            description: user id of the participant to remove
      operationId: mib.resources.lottery.remove_participant
      responses:
        200:
          description: participant succesfully deleted
components: 
  schemas:
    Participant:
      required:
        - id
        - choice
      type: object
      properties:
        id:
          type: integer
          description: unique identifier of a participant, corresponds to the id in the User db
          example: 2
        choice:
          type: integer
          minimum: 1
          maximum: 50
    Lottery:
      required:
        - date
        - participants
      type: object
      properties:
        date:
          type: string
          format: date 
          pattern: /([0-9]{2})/(?:[0-9]{2})/([0-9]{4})/
          example: "01/01/2000"
        participants:
          type: array
          items:
            $ref: '#/components/schemas/Participant'