openapi: "3.0.1"
info:
  title: Users Service API
  description: Users Microservice of Message in a Bottle Application
  version: "0.1"

servers:
  - url: /

paths:
  /lottery:
    get:
      summary: get the next lottery date and the list of participants
      operationId: mib.resources.lottery.get_next_lottery
      responses:
        200:
          description: returns the next lottery date and the participants
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lottery'
  
  /lottery/participate:
    put:
      summary: participate in the next lottery
      tags:
        - Lottery
      operationId: mib.resources.lottery.participate
      requestBody:
        description: creates a new LotteryParticipant with the given email and choice
        required: true
        content: 
          application/json:
            schema:
              $ref: '#/components/schemas/Participant'
      responses:
        200:
          description: Already participated
        400:
          description: Invalid choice
        201:
          description: Lottery participation added        

components:
  schemas:
    Participant:
      required:
        - email
        - choice
      type: object
      properties:
        email:
          type: string
          description: email of participant
          example: example@example.com
        choice:
          type: integer
          minimum: 1
          maximum: 50
    Lottery:
      required:
        - date
        - participants
      type: object
      properties:
        date:
          type: string
          format: date 
          pattern: /([0-9]{2})/(?:[0-9]{2})/([0-9]{4})/
          example: "01/01/2000"
        participants:
          type: array
          items:
            $ref: '#/components/schemas/Participant'